apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    {{- include "cert-manager-resources.labels" . | nindent 4 }}
  name: letsencrypt
spec:
  acme:
    # Email address used for ACME registration
    email: kshuleshov.gcp@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # The ACME server URL
    server: {{ .Values.clusterissuer.server }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
