{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ingress-host-manager.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ingress-host-manager.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-host-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}