{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ingress-host-manager.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ingress-host-manager.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ingress-host-manager.serviceAccountName" . }}
{{ end }}